apiVersion: v2
name: querydoc
description: Document query MCP server for kagent
type: application
version: ${VERSION}
appVersion: v2.15.1
sources:
  - https://github.com/kagent-dev/doc2vec
  - https://github.com/kagent-dev/kagent