# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from kagent.api.v1alpha1 import agents_pb2 as kagent_dot_api_dot_v1alpha1_dot_agents__pb2


class AgentServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListAgents = channel.unary_unary(
                '/kagent.api.v1alpha1.AgentService/ListAgents',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.ListAgentsRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.ListAgentsResponse.FromString,
                _registered_method=True)
        self.GetAgent = channel.unary_unary(
                '/kagent.api.v1alpha1.AgentService/GetAgent',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.GetAgentRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.GetAgentResponse.FromString,
                _registered_method=True)
        self.CreateAgent = channel.unary_unary(
                '/kagent.api.v1alpha1.AgentService/CreateAgent',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.CreateAgentRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.CreateAgentResponse.FromString,
                _registered_method=True)
        self.UpdateAgent = channel.unary_unary(
                '/kagent.api.v1alpha1.AgentService/UpdateAgent',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.UpdateAgentRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.UpdateAgentResponse.FromString,
                _registered_method=True)
        self.DeleteAgent = channel.unary_unary(
                '/kagent.api.v1alpha1.AgentService/DeleteAgent',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.DeleteAgentRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.DeleteAgentResponse.FromString,
                _registered_method=True)
        self.GetSandboxAgent = channel.unary_unary(
                '/kagent.api.v1alpha1.AgentService/GetSandboxAgent',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.GetSandboxAgentRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.GetSandboxAgentResponse.FromString,
                _registered_method=True)
        self.CreateSandboxAgent = channel.unary_unary(
                '/kagent.api.v1alpha1.AgentService/CreateSandboxAgent',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.CreateSandboxAgentRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.CreateSandboxAgentResponse.FromString,
                _registered_method=True)
        self.UpdateSandboxAgent = channel.unary_unary(
                '/kagent.api.v1alpha1.AgentService/UpdateSandboxAgent',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.UpdateSandboxAgentRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.UpdateSandboxAgentResponse.FromString,
                _registered_method=True)
        self.DeleteSandboxAgent = channel.unary_unary(
                '/kagent.api.v1alpha1.AgentService/DeleteSandboxAgent',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.DeleteSandboxAgentRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.DeleteSandboxAgentResponse.FromString,
                _registered_method=True)
        self.GetAgentHarness = channel.unary_unary(
                '/kagent.api.v1alpha1.AgentService/GetAgentHarness',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.GetAgentHarnessRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.GetAgentHarnessResponse.FromString,
                _registered_method=True)
        self.CreateAgentHarness = channel.unary_unary(
                '/kagent.api.v1alpha1.AgentService/CreateAgentHarness',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.CreateAgentHarnessRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.CreateAgentHarnessResponse.FromString,
                _registered_method=True)
        self.DeleteAgentHarness = channel.unary_unary(
                '/kagent.api.v1alpha1.AgentService/DeleteAgentHarness',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.DeleteAgentHarnessRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.DeleteAgentHarnessResponse.FromString,
                _registered_method=True)
        self.EnsureAgentHarnessSessionActor = channel.unary_unary(
                '/kagent.api.v1alpha1.AgentService/EnsureAgentHarnessSessionActor',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.EnsureAgentHarnessSessionActorRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.EnsureAgentHarnessSessionActorResponse.FromString,
                _registered_method=True)
        self.SuspendAgentHarnessSessionActor = channel.unary_unary(
                '/kagent.api.v1alpha1.AgentService/SuspendAgentHarnessSessionActor',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.SuspendAgentHarnessSessionActorRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.SuspendAgentHarnessSessionActorResponse.FromString,
                _registered_method=True)
        self.GetAgentHarnessSessionActor = channel.unary_unary(
                '/kagent.api.v1alpha1.AgentService/GetAgentHarnessSessionActor',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.GetAgentHarnessSessionActorRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.GetAgentHarnessSessionActorResponse.FromString,
                _registered_method=True)


class AgentServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ListAgents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSandboxAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSandboxAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSandboxAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSandboxAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgentHarness(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAgentHarness(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAgentHarness(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnsureAgentHarnessSessionActor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SuspendAgentHarnessSessionActor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgentHarnessSessionActor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListAgents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAgents,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.ListAgentsRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.ListAgentsResponse.SerializeToString,
            ),
            'GetAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgent,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.GetAgentRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.GetAgentResponse.SerializeToString,
            ),
            'CreateAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAgent,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.CreateAgentRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.CreateAgentResponse.SerializeToString,
            ),
            'UpdateAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAgent,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.UpdateAgentRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.UpdateAgentResponse.SerializeToString,
            ),
            'DeleteAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAgent,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.DeleteAgentRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.DeleteAgentResponse.SerializeToString,
            ),
            'GetSandboxAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSandboxAgent,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.GetSandboxAgentRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.GetSandboxAgentResponse.SerializeToString,
            ),
            'CreateSandboxAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSandboxAgent,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.CreateSandboxAgentRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.CreateSandboxAgentResponse.SerializeToString,
            ),
            'UpdateSandboxAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSandboxAgent,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.UpdateSandboxAgentRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.UpdateSandboxAgentResponse.SerializeToString,
            ),
            'DeleteSandboxAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSandboxAgent,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.DeleteSandboxAgentRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.DeleteSandboxAgentResponse.SerializeToString,
            ),
            'GetAgentHarness': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgentHarness,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.GetAgentHarnessRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.GetAgentHarnessResponse.SerializeToString,
            ),
            'CreateAgentHarness': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAgentHarness,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.CreateAgentHarnessRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.CreateAgentHarnessResponse.SerializeToString,
            ),
            'DeleteAgentHarness': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAgentHarness,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.DeleteAgentHarnessRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.DeleteAgentHarnessResponse.SerializeToString,
            ),
            'EnsureAgentHarnessSessionActor': grpc.unary_unary_rpc_method_handler(
                    servicer.EnsureAgentHarnessSessionActor,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.EnsureAgentHarnessSessionActorRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.EnsureAgentHarnessSessionActorResponse.SerializeToString,
            ),
            'SuspendAgentHarnessSessionActor': grpc.unary_unary_rpc_method_handler(
                    servicer.SuspendAgentHarnessSessionActor,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.SuspendAgentHarnessSessionActorRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.SuspendAgentHarnessSessionActorResponse.SerializeToString,
            ),
            'GetAgentHarnessSessionActor': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgentHarnessSessionActor,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.GetAgentHarnessSessionActorRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_agents__pb2.GetAgentHarnessSessionActorResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kagent.api.v1alpha1.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kagent.api.v1alpha1.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListAgents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.AgentService/ListAgents',
            kagent_dot_api_dot_v1alpha1_dot_agents__pb2.ListAgentsRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_agents__pb2.ListAgentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.AgentService/GetAgent',
            kagent_dot_api_dot_v1alpha1_dot_agents__pb2.GetAgentRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_agents__pb2.GetAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.AgentService/CreateAgent',
            kagent_dot_api_dot_v1alpha1_dot_agents__pb2.CreateAgentRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_agents__pb2.CreateAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.AgentService/UpdateAgent',
            kagent_dot_api_dot_v1alpha1_dot_agents__pb2.UpdateAgentRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_agents__pb2.UpdateAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.AgentService/DeleteAgent',
            kagent_dot_api_dot_v1alpha1_dot_agents__pb2.DeleteAgentRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_agents__pb2.DeleteAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSandboxAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.AgentService/GetSandboxAgent',
            kagent_dot_api_dot_v1alpha1_dot_agents__pb2.GetSandboxAgentRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_agents__pb2.GetSandboxAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSandboxAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.AgentService/CreateSandboxAgent',
            kagent_dot_api_dot_v1alpha1_dot_agents__pb2.CreateSandboxAgentRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_agents__pb2.CreateSandboxAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSandboxAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.AgentService/UpdateSandboxAgent',
            kagent_dot_api_dot_v1alpha1_dot_agents__pb2.UpdateSandboxAgentRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_agents__pb2.UpdateSandboxAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSandboxAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.AgentService/DeleteSandboxAgent',
            kagent_dot_api_dot_v1alpha1_dot_agents__pb2.DeleteSandboxAgentRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_agents__pb2.DeleteSandboxAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAgentHarness(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.AgentService/GetAgentHarness',
            kagent_dot_api_dot_v1alpha1_dot_agents__pb2.GetAgentHarnessRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_agents__pb2.GetAgentHarnessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAgentHarness(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.AgentService/CreateAgentHarness',
            kagent_dot_api_dot_v1alpha1_dot_agents__pb2.CreateAgentHarnessRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_agents__pb2.CreateAgentHarnessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAgentHarness(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.AgentService/DeleteAgentHarness',
            kagent_dot_api_dot_v1alpha1_dot_agents__pb2.DeleteAgentHarnessRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_agents__pb2.DeleteAgentHarnessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnsureAgentHarnessSessionActor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.AgentService/EnsureAgentHarnessSessionActor',
            kagent_dot_api_dot_v1alpha1_dot_agents__pb2.EnsureAgentHarnessSessionActorRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_agents__pb2.EnsureAgentHarnessSessionActorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SuspendAgentHarnessSessionActor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.AgentService/SuspendAgentHarnessSessionActor',
            kagent_dot_api_dot_v1alpha1_dot_agents__pb2.SuspendAgentHarnessSessionActorRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_agents__pb2.SuspendAgentHarnessSessionActorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAgentHarnessSessionActor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.AgentService/GetAgentHarnessSessionActor',
            kagent_dot_api_dot_v1alpha1_dot_agents__pb2.GetAgentHarnessSessionActorRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_agents__pb2.GetAgentHarnessSessionActorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
