# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from kagent.api.v1alpha1 import crewai_pb2 as kagent_dot_api_dot_v1alpha1_dot_crewai__pb2


class CrewAIServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StoreMemory = channel.unary_unary(
                '/kagent.api.v1alpha1.CrewAIService/StoreMemory',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_crewai__pb2.StoreMemoryRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_crewai__pb2.StoreMemoryResponse.FromString,
                _registered_method=True)
        self.GetMemory = channel.unary_unary(
                '/kagent.api.v1alpha1.CrewAIService/GetMemory',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_crewai__pb2.GetMemoryRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_crewai__pb2.GetMemoryResponse.FromString,
                _registered_method=True)
        self.ResetMemory = channel.unary_unary(
                '/kagent.api.v1alpha1.CrewAIService/ResetMemory',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_crewai__pb2.ResetMemoryRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_crewai__pb2.ResetMemoryResponse.FromString,
                _registered_method=True)
        self.StoreFlowState = channel.unary_unary(
                '/kagent.api.v1alpha1.CrewAIService/StoreFlowState',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_crewai__pb2.StoreFlowStateRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_crewai__pb2.StoreFlowStateResponse.FromString,
                _registered_method=True)
        self.GetFlowState = channel.unary_unary(
                '/kagent.api.v1alpha1.CrewAIService/GetFlowState',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_crewai__pb2.GetFlowStateRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_crewai__pb2.GetFlowStateResponse.FromString,
                _registered_method=True)


class CrewAIServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def StoreMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreFlowState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFlowState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CrewAIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StoreMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreMemory,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_crewai__pb2.StoreMemoryRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_crewai__pb2.StoreMemoryResponse.SerializeToString,
            ),
            'GetMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMemory,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_crewai__pb2.GetMemoryRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_crewai__pb2.GetMemoryResponse.SerializeToString,
            ),
            'ResetMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetMemory,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_crewai__pb2.ResetMemoryRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_crewai__pb2.ResetMemoryResponse.SerializeToString,
            ),
            'StoreFlowState': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreFlowState,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_crewai__pb2.StoreFlowStateRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_crewai__pb2.StoreFlowStateResponse.SerializeToString,
            ),
            'GetFlowState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFlowState,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_crewai__pb2.GetFlowStateRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_crewai__pb2.GetFlowStateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kagent.api.v1alpha1.CrewAIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kagent.api.v1alpha1.CrewAIService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CrewAIService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StoreMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.CrewAIService/StoreMemory',
            kagent_dot_api_dot_v1alpha1_dot_crewai__pb2.StoreMemoryRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_crewai__pb2.StoreMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.CrewAIService/GetMemory',
            kagent_dot_api_dot_v1alpha1_dot_crewai__pb2.GetMemoryRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_crewai__pb2.GetMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.CrewAIService/ResetMemory',
            kagent_dot_api_dot_v1alpha1_dot_crewai__pb2.ResetMemoryRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_crewai__pb2.ResetMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreFlowState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.CrewAIService/StoreFlowState',
            kagent_dot_api_dot_v1alpha1_dot_crewai__pb2.StoreFlowStateRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_crewai__pb2.StoreFlowStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFlowState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.CrewAIService/GetFlowState',
            kagent_dot_api_dot_v1alpha1_dot_crewai__pb2.GetFlowStateRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_crewai__pb2.GetFlowStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
