# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kagent/api/v1alpha1/feedback.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'kagent/api/v1alpha1/feedback.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"kagent/api/v1alpha1/feedback.proto\x12\x13kagent.api.v1alpha1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x90\x03\n\x08\x46\x65\x65\x64\x62\x61\x63k\x12\x0e\n\x02id\x18\x01 \x01(\x03R\x02id\x12\x39\n\ncreated_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x39\n\nupdated_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x39\n\ndeleted_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tdeletedAt\x12\x17\n\x07user_id\x18\x05 \x01(\tR\x06userId\x12\"\n\nmessage_id\x18\x06 \x01(\x03H\x00R\tmessageId\x88\x01\x01\x12\x1f\n\x0bis_positive\x18\x07 \x01(\x08R\nisPositive\x12#\n\rfeedback_text\x18\x08 \x01(\tR\x0c\x66\x65\x65\x64\x62\x61\x63kText\x12\"\n\nissue_type\x18\t \x01(\tH\x01R\tissueType\x88\x01\x01\x42\r\n\x0b_message_idB\r\n\x0b_issue_type\"\xc3\x01\n\x15\x43reateFeedbackRequest\x12\"\n\nmessage_id\x18\x01 \x01(\x03H\x00R\tmessageId\x88\x01\x01\x12\x1f\n\x0bis_positive\x18\x02 \x01(\x08R\nisPositive\x12#\n\rfeedback_text\x18\x03 \x01(\tR\x0c\x66\x65\x65\x64\x62\x61\x63kText\x12\"\n\nissue_type\x18\x04 \x01(\tH\x01R\tissueType\x88\x01\x01\x42\r\n\x0b_message_idB\r\n\x0b_issue_type\"\x18\n\x16\x43reateFeedbackResponse\"\x15\n\x13ListFeedbackRequest\"Q\n\x14ListFeedbackResponse\x12\x39\n\x08\x66\x65\x65\x64\x62\x61\x63k\x18\x01 \x03(\x0b\x32\x1d.kagent.api.v1alpha1.FeedbackR\x08\x66\x65\x65\x64\x62\x61\x63k2\xe1\x01\n\x0f\x46\x65\x65\x64\x62\x61\x63kService\x12i\n\x0e\x43reateFeedback\x12*.kagent.api.v1alpha1.CreateFeedbackRequest\x1a+.kagent.api.v1alpha1.CreateFeedbackResponse\x12\x63\n\x0cListFeedback\x12(.kagent.api.v1alpha1.ListFeedbackRequest\x1a).kagent.api.v1alpha1.ListFeedbackResponseBIZGgithub.com/kagent-dev/kagent/go/api/gen/kagent/api/v1alpha1;apiv1alpha1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kagent.api.v1alpha1.feedback_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZGgithub.com/kagent-dev/kagent/go/api/gen/kagent/api/v1alpha1;apiv1alpha1'
  _globals['_FEEDBACK']._serialized_start=93
  _globals['_FEEDBACK']._serialized_end=493
  _globals['_CREATEFEEDBACKREQUEST']._serialized_start=496
  _globals['_CREATEFEEDBACKREQUEST']._serialized_end=691
  _globals['_CREATEFEEDBACKRESPONSE']._serialized_start=693
  _globals['_CREATEFEEDBACKRESPONSE']._serialized_end=717
  _globals['_LISTFEEDBACKREQUEST']._serialized_start=719
  _globals['_LISTFEEDBACKREQUEST']._serialized_end=740
  _globals['_LISTFEEDBACKRESPONSE']._serialized_start=742
  _globals['_LISTFEEDBACKRESPONSE']._serialized_end=823
  _globals['_FEEDBACKSERVICE']._serialized_start=826
  _globals['_FEEDBACKSERVICE']._serialized_end=1051
# @@protoc_insertion_point(module_scope)
