# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from kagent.api.v1alpha1 import feedback_pb2 as kagent_dot_api_dot_v1alpha1_dot_feedback__pb2


class FeedbackServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateFeedback = channel.unary_unary(
                '/kagent.api.v1alpha1.FeedbackService/CreateFeedback',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_feedback__pb2.CreateFeedbackRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_feedback__pb2.CreateFeedbackResponse.FromString,
                _registered_method=True)
        self.ListFeedback = channel.unary_unary(
                '/kagent.api.v1alpha1.FeedbackService/ListFeedback',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_feedback__pb2.ListFeedbackRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_feedback__pb2.ListFeedbackResponse.FromString,
                _registered_method=True)


class FeedbackServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateFeedback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFeedback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FeedbackServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateFeedback': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateFeedback,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_feedback__pb2.CreateFeedbackRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_feedback__pb2.CreateFeedbackResponse.SerializeToString,
            ),
            'ListFeedback': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFeedback,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_feedback__pb2.ListFeedbackRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_feedback__pb2.ListFeedbackResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kagent.api.v1alpha1.FeedbackService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kagent.api.v1alpha1.FeedbackService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FeedbackService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateFeedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.FeedbackService/CreateFeedback',
            kagent_dot_api_dot_v1alpha1_dot_feedback__pb2.CreateFeedbackRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_feedback__pb2.CreateFeedbackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFeedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.FeedbackService/ListFeedback',
            kagent_dot_api_dot_v1alpha1_dot_feedback__pb2.ListFeedbackRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_feedback__pb2.ListFeedbackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
