# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from kagent.api.v1alpha1 import langgraph_pb2 as kagent_dot_api_dot_v1alpha1_dot_langgraph__pb2


class LangGraphServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PutCheckpoint = channel.unary_unary(
                '/kagent.api.v1alpha1.LangGraphService/PutCheckpoint',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_langgraph__pb2.PutCheckpointRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_langgraph__pb2.PutCheckpointResponse.FromString,
                _registered_method=True)
        self.ListCheckpoints = channel.unary_unary(
                '/kagent.api.v1alpha1.LangGraphService/ListCheckpoints',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_langgraph__pb2.ListCheckpointsRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_langgraph__pb2.ListCheckpointsResponse.FromString,
                _registered_method=True)
        self.PutWrites = channel.unary_unary(
                '/kagent.api.v1alpha1.LangGraphService/PutWrites',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_langgraph__pb2.PutWritesRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_langgraph__pb2.PutWritesResponse.FromString,
                _registered_method=True)
        self.DeleteThread = channel.unary_unary(
                '/kagent.api.v1alpha1.LangGraphService/DeleteThread',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_langgraph__pb2.DeleteThreadRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_langgraph__pb2.DeleteThreadResponse.FromString,
                _registered_method=True)


class LangGraphServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def PutCheckpoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCheckpoints(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutWrites(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteThread(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LangGraphServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PutCheckpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.PutCheckpoint,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_langgraph__pb2.PutCheckpointRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_langgraph__pb2.PutCheckpointResponse.SerializeToString,
            ),
            'ListCheckpoints': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCheckpoints,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_langgraph__pb2.ListCheckpointsRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_langgraph__pb2.ListCheckpointsResponse.SerializeToString,
            ),
            'PutWrites': grpc.unary_unary_rpc_method_handler(
                    servicer.PutWrites,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_langgraph__pb2.PutWritesRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_langgraph__pb2.PutWritesResponse.SerializeToString,
            ),
            'DeleteThread': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteThread,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_langgraph__pb2.DeleteThreadRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_langgraph__pb2.DeleteThreadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kagent.api.v1alpha1.LangGraphService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kagent.api.v1alpha1.LangGraphService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LangGraphService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PutCheckpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.LangGraphService/PutCheckpoint',
            kagent_dot_api_dot_v1alpha1_dot_langgraph__pb2.PutCheckpointRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_langgraph__pb2.PutCheckpointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCheckpoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.LangGraphService/ListCheckpoints',
            kagent_dot_api_dot_v1alpha1_dot_langgraph__pb2.ListCheckpointsRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_langgraph__pb2.ListCheckpointsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PutWrites(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.LangGraphService/PutWrites',
            kagent_dot_api_dot_v1alpha1_dot_langgraph__pb2.PutWritesRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_langgraph__pb2.PutWritesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteThread(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.LangGraphService/DeleteThread',
            kagent_dot_api_dot_v1alpha1_dot_langgraph__pb2.DeleteThreadRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_langgraph__pb2.DeleteThreadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
