# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from kagent.api.v1alpha1 import models_pb2 as kagent_dot_api_dot_v1alpha1_dot_models__pb2


class ModelServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListModelConfigs = channel.unary_unary(
                '/kagent.api.v1alpha1.ModelService/ListModelConfigs',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_models__pb2.ListModelConfigsRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_models__pb2.ListModelConfigsResponse.FromString,
                _registered_method=True)
        self.GetModelConfig = channel.unary_unary(
                '/kagent.api.v1alpha1.ModelService/GetModelConfig',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_models__pb2.GetModelConfigRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_models__pb2.GetModelConfigResponse.FromString,
                _registered_method=True)
        self.CreateModelConfig = channel.unary_unary(
                '/kagent.api.v1alpha1.ModelService/CreateModelConfig',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_models__pb2.CreateModelConfigRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_models__pb2.CreateModelConfigResponse.FromString,
                _registered_method=True)
        self.UpdateModelConfig = channel.unary_unary(
                '/kagent.api.v1alpha1.ModelService/UpdateModelConfig',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_models__pb2.UpdateModelConfigRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_models__pb2.UpdateModelConfigResponse.FromString,
                _registered_method=True)
        self.DeleteModelConfig = channel.unary_unary(
                '/kagent.api.v1alpha1.ModelService/DeleteModelConfig',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_models__pb2.DeleteModelConfigRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_models__pb2.DeleteModelConfigResponse.FromString,
                _registered_method=True)
        self.ListSupportedModelProviders = channel.unary_unary(
                '/kagent.api.v1alpha1.ModelService/ListSupportedModelProviders',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_models__pb2.ListSupportedModelProvidersRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_models__pb2.ListSupportedModelProvidersResponse.FromString,
                _registered_method=True)
        self.ListSupportedMemoryProviders = channel.unary_unary(
                '/kagent.api.v1alpha1.ModelService/ListSupportedMemoryProviders',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_models__pb2.ListSupportedMemoryProvidersRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_models__pb2.ListSupportedMemoryProvidersResponse.FromString,
                _registered_method=True)
        self.ListConfiguredProviders = channel.unary_unary(
                '/kagent.api.v1alpha1.ModelService/ListConfiguredProviders',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_models__pb2.ListConfiguredProvidersRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_models__pb2.ListConfiguredProvidersResponse.FromString,
                _registered_method=True)
        self.ListProviderModels = channel.unary_unary(
                '/kagent.api.v1alpha1.ModelService/ListProviderModels',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_models__pb2.ListProviderModelsRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_models__pb2.ListProviderModelsResponse.FromString,
                _registered_method=True)
        self.ListSupportedModels = channel.unary_unary(
                '/kagent.api.v1alpha1.ModelService/ListSupportedModels',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_models__pb2.ListSupportedModelsRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_models__pb2.ListSupportedModelsResponse.FromString,
                _registered_method=True)


class ModelServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ListModelConfigs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateModelConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateModelConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteModelConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSupportedModelProviders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSupportedMemoryProviders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListConfiguredProviders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProviderModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSupportedModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListModelConfigs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModelConfigs,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_models__pb2.ListModelConfigsRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_models__pb2.ListModelConfigsResponse.SerializeToString,
            ),
            'GetModelConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelConfig,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_models__pb2.GetModelConfigRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_models__pb2.GetModelConfigResponse.SerializeToString,
            ),
            'CreateModelConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateModelConfig,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_models__pb2.CreateModelConfigRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_models__pb2.CreateModelConfigResponse.SerializeToString,
            ),
            'UpdateModelConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateModelConfig,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_models__pb2.UpdateModelConfigRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_models__pb2.UpdateModelConfigResponse.SerializeToString,
            ),
            'DeleteModelConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteModelConfig,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_models__pb2.DeleteModelConfigRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_models__pb2.DeleteModelConfigResponse.SerializeToString,
            ),
            'ListSupportedModelProviders': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSupportedModelProviders,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_models__pb2.ListSupportedModelProvidersRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_models__pb2.ListSupportedModelProvidersResponse.SerializeToString,
            ),
            'ListSupportedMemoryProviders': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSupportedMemoryProviders,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_models__pb2.ListSupportedMemoryProvidersRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_models__pb2.ListSupportedMemoryProvidersResponse.SerializeToString,
            ),
            'ListConfiguredProviders': grpc.unary_unary_rpc_method_handler(
                    servicer.ListConfiguredProviders,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_models__pb2.ListConfiguredProvidersRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_models__pb2.ListConfiguredProvidersResponse.SerializeToString,
            ),
            'ListProviderModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProviderModels,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_models__pb2.ListProviderModelsRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_models__pb2.ListProviderModelsResponse.SerializeToString,
            ),
            'ListSupportedModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSupportedModels,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_models__pb2.ListSupportedModelsRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_models__pb2.ListSupportedModelsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kagent.api.v1alpha1.ModelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kagent.api.v1alpha1.ModelService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ModelService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListModelConfigs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.ModelService/ListModelConfigs',
            kagent_dot_api_dot_v1alpha1_dot_models__pb2.ListModelConfigsRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_models__pb2.ListModelConfigsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.ModelService/GetModelConfig',
            kagent_dot_api_dot_v1alpha1_dot_models__pb2.GetModelConfigRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_models__pb2.GetModelConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateModelConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.ModelService/CreateModelConfig',
            kagent_dot_api_dot_v1alpha1_dot_models__pb2.CreateModelConfigRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_models__pb2.CreateModelConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateModelConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.ModelService/UpdateModelConfig',
            kagent_dot_api_dot_v1alpha1_dot_models__pb2.UpdateModelConfigRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_models__pb2.UpdateModelConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteModelConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.ModelService/DeleteModelConfig',
            kagent_dot_api_dot_v1alpha1_dot_models__pb2.DeleteModelConfigRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_models__pb2.DeleteModelConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSupportedModelProviders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.ModelService/ListSupportedModelProviders',
            kagent_dot_api_dot_v1alpha1_dot_models__pb2.ListSupportedModelProvidersRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_models__pb2.ListSupportedModelProvidersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSupportedMemoryProviders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.ModelService/ListSupportedMemoryProviders',
            kagent_dot_api_dot_v1alpha1_dot_models__pb2.ListSupportedMemoryProvidersRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_models__pb2.ListSupportedMemoryProvidersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListConfiguredProviders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.ModelService/ListConfiguredProviders',
            kagent_dot_api_dot_v1alpha1_dot_models__pb2.ListConfiguredProvidersRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_models__pb2.ListConfiguredProvidersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProviderModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.ModelService/ListProviderModels',
            kagent_dot_api_dot_v1alpha1_dot_models__pb2.ListProviderModelsRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_models__pb2.ListProviderModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSupportedModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.ModelService/ListSupportedModels',
            kagent_dot_api_dot_v1alpha1_dot_models__pb2.ListSupportedModelsRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_models__pb2.ListSupportedModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
