# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from kagent.api.v1alpha1 import prompts_pb2 as kagent_dot_api_dot_v1alpha1_dot_prompts__pb2


class PromptTemplateServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListPromptTemplates = channel.unary_unary(
                '/kagent.api.v1alpha1.PromptTemplateService/ListPromptTemplates',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_prompts__pb2.ListPromptTemplatesRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_prompts__pb2.ListPromptTemplatesResponse.FromString,
                _registered_method=True)
        self.GetPromptTemplate = channel.unary_unary(
                '/kagent.api.v1alpha1.PromptTemplateService/GetPromptTemplate',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_prompts__pb2.GetPromptTemplateRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_prompts__pb2.GetPromptTemplateResponse.FromString,
                _registered_method=True)
        self.CreatePromptTemplate = channel.unary_unary(
                '/kagent.api.v1alpha1.PromptTemplateService/CreatePromptTemplate',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_prompts__pb2.CreatePromptTemplateRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_prompts__pb2.CreatePromptTemplateResponse.FromString,
                _registered_method=True)
        self.UpdatePromptTemplate = channel.unary_unary(
                '/kagent.api.v1alpha1.PromptTemplateService/UpdatePromptTemplate',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_prompts__pb2.UpdatePromptTemplateRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_prompts__pb2.UpdatePromptTemplateResponse.FromString,
                _registered_method=True)
        self.DeletePromptTemplate = channel.unary_unary(
                '/kagent.api.v1alpha1.PromptTemplateService/DeletePromptTemplate',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_prompts__pb2.DeletePromptTemplateRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_prompts__pb2.DeletePromptTemplateResponse.FromString,
                _registered_method=True)


class PromptTemplateServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ListPromptTemplates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPromptTemplate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePromptTemplate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePromptTemplate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePromptTemplate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PromptTemplateServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListPromptTemplates': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPromptTemplates,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_prompts__pb2.ListPromptTemplatesRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_prompts__pb2.ListPromptTemplatesResponse.SerializeToString,
            ),
            'GetPromptTemplate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPromptTemplate,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_prompts__pb2.GetPromptTemplateRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_prompts__pb2.GetPromptTemplateResponse.SerializeToString,
            ),
            'CreatePromptTemplate': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePromptTemplate,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_prompts__pb2.CreatePromptTemplateRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_prompts__pb2.CreatePromptTemplateResponse.SerializeToString,
            ),
            'UpdatePromptTemplate': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePromptTemplate,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_prompts__pb2.UpdatePromptTemplateRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_prompts__pb2.UpdatePromptTemplateResponse.SerializeToString,
            ),
            'DeletePromptTemplate': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePromptTemplate,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_prompts__pb2.DeletePromptTemplateRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_prompts__pb2.DeletePromptTemplateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kagent.api.v1alpha1.PromptTemplateService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kagent.api.v1alpha1.PromptTemplateService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PromptTemplateService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListPromptTemplates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.PromptTemplateService/ListPromptTemplates',
            kagent_dot_api_dot_v1alpha1_dot_prompts__pb2.ListPromptTemplatesRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_prompts__pb2.ListPromptTemplatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPromptTemplate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.PromptTemplateService/GetPromptTemplate',
            kagent_dot_api_dot_v1alpha1_dot_prompts__pb2.GetPromptTemplateRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_prompts__pb2.GetPromptTemplateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreatePromptTemplate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.PromptTemplateService/CreatePromptTemplate',
            kagent_dot_api_dot_v1alpha1_dot_prompts__pb2.CreatePromptTemplateRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_prompts__pb2.CreatePromptTemplateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePromptTemplate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.PromptTemplateService/UpdatePromptTemplate',
            kagent_dot_api_dot_v1alpha1_dot_prompts__pb2.UpdatePromptTemplateRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_prompts__pb2.UpdatePromptTemplateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePromptTemplate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.PromptTemplateService/DeletePromptTemplate',
            kagent_dot_api_dot_v1alpha1_dot_prompts__pb2.DeletePromptTemplateRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_prompts__pb2.DeletePromptTemplateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
