# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from kagent.api.v1alpha1 import system_pb2 as kagent_dot_api_dot_v1alpha1_dot_system__pb2


class SystemServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetVersion = channel.unary_unary(
                '/kagent.api.v1alpha1.SystemService/GetVersion',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_system__pb2.GetVersionRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_system__pb2.GetVersionResponse.FromString,
                _registered_method=True)
        self.GetCurrentUser = channel.unary_unary(
                '/kagent.api.v1alpha1.SystemService/GetCurrentUser',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_system__pb2.GetCurrentUserRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_system__pb2.GetCurrentUserResponse.FromString,
                _registered_method=True)
        self.ListNamespaces = channel.unary_unary(
                '/kagent.api.v1alpha1.SystemService/ListNamespaces',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_system__pb2.ListNamespacesRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_system__pb2.ListNamespacesResponse.FromString,
                _registered_method=True)
        self.GetSubstrateStatus = channel.unary_unary(
                '/kagent.api.v1alpha1.SystemService/GetSubstrateStatus',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_system__pb2.GetSubstrateStatusRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_system__pb2.GetSubstrateStatusResponse.FromString,
                _registered_method=True)


class SystemServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCurrentUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListNamespaces(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSubstrateStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SystemServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVersion,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_system__pb2.GetVersionRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_system__pb2.GetVersionResponse.SerializeToString,
            ),
            'GetCurrentUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCurrentUser,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_system__pb2.GetCurrentUserRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_system__pb2.GetCurrentUserResponse.SerializeToString,
            ),
            'ListNamespaces': grpc.unary_unary_rpc_method_handler(
                    servicer.ListNamespaces,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_system__pb2.ListNamespacesRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_system__pb2.ListNamespacesResponse.SerializeToString,
            ),
            'GetSubstrateStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSubstrateStatus,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_system__pb2.GetSubstrateStatusRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_system__pb2.GetSubstrateStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kagent.api.v1alpha1.SystemService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kagent.api.v1alpha1.SystemService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SystemService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.SystemService/GetVersion',
            kagent_dot_api_dot_v1alpha1_dot_system__pb2.GetVersionRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_system__pb2.GetVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCurrentUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.SystemService/GetCurrentUser',
            kagent_dot_api_dot_v1alpha1_dot_system__pb2.GetCurrentUserRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_system__pb2.GetCurrentUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListNamespaces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.SystemService/ListNamespaces',
            kagent_dot_api_dot_v1alpha1_dot_system__pb2.ListNamespacesRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_system__pb2.ListNamespacesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSubstrateStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.SystemService/GetSubstrateStatus',
            kagent_dot_api_dot_v1alpha1_dot_system__pb2.GetSubstrateStatusRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_system__pb2.GetSubstrateStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
