# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from kagent.api.v1alpha1 import tools_pb2 as kagent_dot_api_dot_v1alpha1_dot_tools__pb2


class ToolServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListTools = channel.unary_unary(
                '/kagent.api.v1alpha1.ToolService/ListTools',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_tools__pb2.ListToolsRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_tools__pb2.ListToolsResponse.FromString,
                _registered_method=True)
        self.ListToolServers = channel.unary_unary(
                '/kagent.api.v1alpha1.ToolService/ListToolServers',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_tools__pb2.ListToolServersRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_tools__pb2.ListToolServersResponse.FromString,
                _registered_method=True)
        self.CreateToolServer = channel.unary_unary(
                '/kagent.api.v1alpha1.ToolService/CreateToolServer',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_tools__pb2.CreateToolServerRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_tools__pb2.CreateToolServerResponse.FromString,
                _registered_method=True)
        self.DeleteToolServer = channel.unary_unary(
                '/kagent.api.v1alpha1.ToolService/DeleteToolServer',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_tools__pb2.DeleteToolServerRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_tools__pb2.DeleteToolServerResponse.FromString,
                _registered_method=True)
        self.ListToolServerTypes = channel.unary_unary(
                '/kagent.api.v1alpha1.ToolService/ListToolServerTypes',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_tools__pb2.ListToolServerTypesRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_tools__pb2.ListToolServerTypesResponse.FromString,
                _registered_method=True)
        self.ListMCPAppTools = channel.unary_unary(
                '/kagent.api.v1alpha1.ToolService/ListMCPAppTools',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_tools__pb2.ListMCPAppToolsRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_tools__pb2.ListMCPAppToolsResponse.FromString,
                _registered_method=True)
        self.CallMCPAppTool = channel.unary_unary(
                '/kagent.api.v1alpha1.ToolService/CallMCPAppTool',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_tools__pb2.CallMCPAppToolRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_tools__pb2.CallMCPAppToolResponse.FromString,
                _registered_method=True)
        self.ReadMCPAppResource = channel.unary_unary(
                '/kagent.api.v1alpha1.ToolService/ReadMCPAppResource',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_tools__pb2.ReadMCPAppResourceRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_tools__pb2.ReadMCPAppResourceResponse.FromString,
                _registered_method=True)


class ToolServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ListTools(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListToolServers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateToolServer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteToolServer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListToolServerTypes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMCPAppTools(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CallMCPAppTool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadMCPAppResource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ToolServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListTools': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTools,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_tools__pb2.ListToolsRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_tools__pb2.ListToolsResponse.SerializeToString,
            ),
            'ListToolServers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListToolServers,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_tools__pb2.ListToolServersRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_tools__pb2.ListToolServersResponse.SerializeToString,
            ),
            'CreateToolServer': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateToolServer,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_tools__pb2.CreateToolServerRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_tools__pb2.CreateToolServerResponse.SerializeToString,
            ),
            'DeleteToolServer': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteToolServer,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_tools__pb2.DeleteToolServerRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_tools__pb2.DeleteToolServerResponse.SerializeToString,
            ),
            'ListToolServerTypes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListToolServerTypes,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_tools__pb2.ListToolServerTypesRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_tools__pb2.ListToolServerTypesResponse.SerializeToString,
            ),
            'ListMCPAppTools': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMCPAppTools,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_tools__pb2.ListMCPAppToolsRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_tools__pb2.ListMCPAppToolsResponse.SerializeToString,
            ),
            'CallMCPAppTool': grpc.unary_unary_rpc_method_handler(
                    servicer.CallMCPAppTool,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_tools__pb2.CallMCPAppToolRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_tools__pb2.CallMCPAppToolResponse.SerializeToString,
            ),
            'ReadMCPAppResource': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadMCPAppResource,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_tools__pb2.ReadMCPAppResourceRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_tools__pb2.ReadMCPAppResourceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kagent.api.v1alpha1.ToolService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kagent.api.v1alpha1.ToolService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ToolService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListTools(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.ToolService/ListTools',
            kagent_dot_api_dot_v1alpha1_dot_tools__pb2.ListToolsRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_tools__pb2.ListToolsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListToolServers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.ToolService/ListToolServers',
            kagent_dot_api_dot_v1alpha1_dot_tools__pb2.ListToolServersRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_tools__pb2.ListToolServersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateToolServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.ToolService/CreateToolServer',
            kagent_dot_api_dot_v1alpha1_dot_tools__pb2.CreateToolServerRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_tools__pb2.CreateToolServerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteToolServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.ToolService/DeleteToolServer',
            kagent_dot_api_dot_v1alpha1_dot_tools__pb2.DeleteToolServerRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_tools__pb2.DeleteToolServerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListToolServerTypes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.ToolService/ListToolServerTypes',
            kagent_dot_api_dot_v1alpha1_dot_tools__pb2.ListToolServerTypesRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_tools__pb2.ListToolServerTypesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMCPAppTools(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.ToolService/ListMCPAppTools',
            kagent_dot_api_dot_v1alpha1_dot_tools__pb2.ListMCPAppToolsRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_tools__pb2.ListMCPAppToolsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CallMCPAppTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.ToolService/CallMCPAppTool',
            kagent_dot_api_dot_v1alpha1_dot_tools__pb2.CallMCPAppToolRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_tools__pb2.CallMCPAppToolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadMCPAppResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.ToolService/ReadMCPAppResource',
            kagent_dot_api_dot_v1alpha1_dot_tools__pb2.ReadMCPAppResourceRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_tools__pb2.ReadMCPAppResourceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
