apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: agent-workflow
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: dapr-redis-master.default.svc.cluster.local:6379
  - name: redisPassword
    secretKeyRef:
      name: dapr-redis
      key: redis-password
  - name: actorStateStore
    value: "true"
