apiVersion: v1
kind: Secret
metadata:
  name: dapr-redis
  namespace: default
type: Opaque
data:
  redis-password: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dapr-redis
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dapr-redis
  template:
    metadata:
      labels:
        app: dapr-redis
    spec:
      containers:
      - name: redis
        image: redis:6.2
        ports:
        - containerPort: 6379
        command: ["redis-server"]
        args: ["--protected-mode", "no"]
---
apiVersion: v1
kind: Service
metadata:
  name: dapr-redis-master
  namespace: default
spec:
  selector:
    app: dapr-redis
  ports:
  - port: 6379
    targetPort: 6379
  type: ClusterIP
