replicas: 1

grafana:
  url: "grafana.kagent:3000/api"
  apiKey: "-"

image:
  registry: mcp
  repository: grafana
  pullPolicy: Always 
  tag: "latest" # Only latest is available via docker hub at present. See https://github.com/grafana/mcp-grafana/issues/180

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

securityContext: {}
  
tolerations: []

nodeSelector: {}

service:
  type: ClusterIP
  port: 8000

resources: {}

# Deployment configuration - used to populate the ConfigMap template.
# Add custom configuration values here as needed.
config:

