# -- Configure the runtime for the agent. Defaults to python, but can also be configured as go.
runtime: ""

modelConfigRef: ""
imagePullSecrets: []

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi

