# Values for the kagent-crds chart

# ==============================================================================
# KMCP
# ==============================================================================

kmcp:
  enabled: true