import type { Meta, StoryObj } from "@storybook/nextjs-vite";
import StreamingMessage from "./StreamingMessage";

const meta = {
  title: "Chat/StreamingMessage",
  component: StreamingMessage,
  parameters: {
    layout: "centered",
  },
  tags: ["autodocs"],
} satisfies Meta<typeof StreamingMessage>;

export default meta;
type Story = StoryObj<typeof meta>;

export const ShortStreamingContent: Story = {
  args: {
    content: "Processing your request...",
  },
};

export const LongStreamingContent: Story = {
  args: {
    content: `I'm analyzing your request and generating a comprehensive response. This content is being streamed in real-time as it's being generated by the AI model. The streaming indicator shows that more content may be arriving...`,
  },
};

export const StreamingWithMarkdown: Story = {
  args: {
    content: `# Analysis Results

I'm currently analyzing the data and here's what I found so far:

## Key Findings
- Finding 1 is being processed
- Finding 2 is being analyzed
- More findings are coming...`,
  },
};

export const StreamingWithCodeBlock: Story = {
  args: {
    content: `Here's the code I'm generating:

\`\`\`python
def process_data(data):
    # Processing logic
    result = []
    for item in data:
        # More logic being generated...`,
  },
};

export const EmptyContent: Story = {
  args: {
    content: "",
  },
  render: (args) => {
    const result = StreamingMessage(args);
    return result === null ? <div className="text-gray-500">Component returns null for empty content</div> : result;
  },
};

export const SingleCharacter: Story = {
  args: {
    content: "A",
  },
};

export const StreamingWithList: Story = {
  args: {
    content: `Generating a list of items:

1. First item
2. Second item
3. Third item (still generating...`,
  },
};
