apiVersion: kagent.dev/v1alpha2
kind: RemoteMCPServer
metadata:
  name: {{ include "querydoc.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "querydoc.labels" . | nindent 4 }}
spec:
  url: {{ include "querydoc.serverUrl" . }}
  timeout: 30s
  protocol: STREAMABLE_HTTP
  description: "Documentation Query Tool Server"
