[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "kagent-crewai"
version = "0.1.0"
description = "CrewAI integration for KAgent with A2A server support"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "crewai[tools]>= 1.2.0",
  "instructor",
  "httpx>=0.25.0",
  "fastapi>=0.100.0",
  "pydantic>=2.0.0",
  "typing-extensions>=4.0.0",
  "uvicorn>=0.20.0",
  "a2a-sdk[http-server]>=0.3.1",
  "kagent-core",
  "opentelemetry-instrumentation-crewai>=0.47.3",
  "google-genai>=1.21.1"
]


[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-asyncio>=0.21.0",
    "black>=23.0.0",
    "ruff>=0.1.0",
]

[tool.uv.sources]
kagent-core = {workspace = true}
# Need this for openai >= 2.0.0 bump.
instructor = { git = "https://github.com/567-labs/instructor", rev = "67f6ce2" }


[tool.hatch.build.targets.wheel]
packages = ["src/kagent"]

[tool.ruff]
extend = "../../pyproject.toml"