apiVersion: v1
kind: Secret
metadata:
  name: a2a-jwt-secret
  namespace: {{ include "kagent.namespace" . }}
  labels:
    {{- include "kagent.labels" . | nindent 4 }}
type: Opaque
data:
  secret: {{ .Values.a2a.jwtSecret | default (randAlphaNum 32) | b64enc }} 