{{- if ne .Values.providers.createDefaultModelConfig false }}
{{- $dot := . }}
{{- $defaultProvider := $dot.Values.providers.default | default "openAI" }}
{{- if hasKey $dot.Values.providers $defaultProvider | not }}
{{- fail (printf "Provider key=%s is not found under .Values.providers" $defaultProvider) }}
{{- end }}
{{- $model := index $dot.Values.providers $defaultProvider }}
{{- if and $model.apiKeySecretRef $model.apiKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $model.apiKeySecretRef | quote }}
  namespace: {{ include "kagent.namespace" . }}
  labels:
    {{- include "kagent.labels" $dot | nindent 4 }}
type: Opaque
data:
  {{ $model.apiKeySecretKey | default (printf "%s_API_KEY" $model.provider | upper) }}: {{ $model.apiKey | b64enc }}
{{- end }}
{{- end }}
