apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kagent.fullname" . }}-nginx-config
  namespace: {{ include "kagent.namespace" . }}
  labels:
    {{- include "kagent.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
data:
  nginx.conf: |-
    events {
        worker_connections 1024;
    }
    http {
        upstream kagent_ui {
            server 127.0.0.1:8001;
        }
        upstream kagent_ws_backend {
            server 127.0.0.1:8081;
        }
        upstream kagent_backend {
            server 127.0.0.1:8083;
        }
{{- if .Values.oauth2Proxy.enabled }}
        upstream oauth2_proxy {
            server 127.0.0.1:4180;
        }
{{- end }}
        map $http_upgrade $connection_upgrade {
            default upgrade;
            "" close;
        }
        server {
            listen 8080;
            server_name localhost;
{{- if .Values.oauth2Proxy.enabled }}
            location /oauth2/ {
                proxy_pass http://oauth2_proxy;
            }
            location / {
                auth_request /oauth2/auth;
                proxy_pass http://kagent_ui;
            }
{{- else }}
            location / {
                proxy_pass http://kagent_ui;
            }
{{- end }}
        }
    } 
