{{- if and .Values.oauth2Proxy.enabled (not .Values.oauth2Proxy.secrets.external) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.oauth2Proxy.secrets.secretName }}
  namespace: {{ include "kagent.namespace" . }}
  labels:
    {{- include "kagent.labels" . | nindent 4 }}
    app.kubernetes.io/component: oauth2-proxy
type: Opaque
data:
  {{ .Values.oauth2Proxy.secrets.clientIdKey }}: {{ .Values.oauth2Proxy.clientId | b64enc }}
  {{ .Values.oauth2Proxy.secrets.clientSecretKey }}: {{ .Values.oauth2Proxy.clientSecret | b64enc }}
  {{ .Values.oauth2Proxy.secrets.cookieSecretKey }}: {{ .Values.oauth2Proxy.cookieSecret | b64enc }}
{{- end }} 
