{{- if and .Values.database.postgres.bundled.enabled (eq .Values.database.postgres.url "") (eq .Values.database.postgres.urlFile "") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kagent.passwordSecretName" . }}
  namespace: {{ include "kagent.namespace" . }}
  labels:
    app.kubernetes.io/component: database
type: Opaque
data:
  POSTGRES_PASSWORD: {{ "kagent" | b64enc | quote }}
{{- end }}
