{{- if .Values.database.postgres.bundled.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kagent.postgresqlServiceName" . }}
  namespace: {{ include "kagent.namespace" . }}
  labels:
    {{- include "kagent.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
{{- end }}
