{{- if eq .Values.modelconfig.default.provider "OpenAI" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.modelconfig.default.openai.secretName | quote }}
  labels:
    {{- include "kagent.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.modelconfig.default.openai.secretKey }}: {{ .Values.modelconfig.default.openai.apiKey | b64enc }}
{{- end }}