apiVersion: v1
kind: Service
metadata:
  name: {{ include "kagent.fullname" . }}
  namespace: {{ include "kagent.namespace" . }}
  labels:
    {{- include "kagent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.oauth2Proxy.enabled }}
    - port: {{ .Values.service.ports.oauth2Proxy.port }}
      targetPort: {{ .Values.service.ports.oauth2Proxy.targetPort }}
      protocol: TCP
      name: oauth2-proxy
    {{- else }}
    - port: {{ .Values.service.ports.ui.port }}
      targetPort: {{ .Values.service.ports.ui.targetPort }}
      protocol: TCP
      name: ui
    {{- end }}
    - port: {{ .Values.service.ports.app.port }}
      targetPort: {{ .Values.service.ports.app.targetPort }}
      protocol: TCP
      name: app
    - port: {{ .Values.service.ports.controller.port }}
      targetPort: {{ .Values.service.ports.controller.targetPort }}
      protocol: TCP
      name: controller
  selector:
    {{- include "kagent.selectorLabels" . | nindent 4 }}
