{{- if and .Values.controller.substrate.enabled .Values.substrateWorkerPool.create (not (include "kagent.substrateWorkerPool.userServiceAccountName" .)) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kagent.substrateWorkerPool.serviceAccountName" . | quote }}
  namespace: {{ include "kagent.namespace" . }}
  labels:
    {{- include "kagent.labels" . | nindent 4 }}
{{- end }}
