apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kagent.fullname" . }}-mcp-grafana
  namespace: {{ include "kagent.namespace" . }}
  labels:
    {{- include "kagent.labels" . | nindent 4 }}
type: Opaque
stringData:
  apiKey: {{ .Values.tools.grafana.apiKey | default "fake" }}
---
apiVersion: kagent.dev/v1alpha1
kind: ToolServer
metadata:
  name: {{ include "kagent.fullname" . }}-mcp-grafana
  namespace: kagent
spec:
  config:
    stdio:
      command: /app/python/bin/mcp-grafana
      args:
        - -t
        - stdio
        - debug
      readTimeoutSeconds: 30
      envFrom:
      - name: "GRAFANA_URL"
        value: {{ .Values.tools.grafana.url | quote }}
      - name: "GRAFANA_API_KEY"
        valueFrom:
          type: Secret
          key: "apiKey"
          valueRef: {{ include "kagent.fullname" . }}-mcp-grafana
  description: "Toolserver for Official Grafana MCP Server"
