apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kagent.fullname" . }}-mcp-grafana
  namespace: {{ include "kagent.namespace" . }}
  labels:
    {{- include "kagent.labels" . | nindent 4 }}
type: Opaque
stringData:
  apiKey: {{ .Values.tools.grafana.apiKey | default "fake" }}
---
apiVersion: kagent.dev/v1alpha1
kind: ToolServer
metadata:
  name: {{ include "kagent.fullname" . }}-mcp-grafana
  namespace: kagent
spec:
  config:
    type: sse
    sse:
      url: {{ printf "http://kagent.%s.svc.cluster.local:%v/sse" .Release.Namespace 8000 }}
      sseReadTimeout: 5m0s
      timeout: 30s
  description: "KAgent Grafana MCP"
