apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kagent.fullname" . }}-mcp-grafana
  namespace: {{ include "kagent.namespace" . }}
  labels:
    {{- include "kagent.labels" . | nindent 4 }}
type: Opaque
stringData:
  apiKey: {{ .Values.tools.grafana.apiKey | default "fake" }}
---
apiVersion: kagent.dev/v1alpha2
kind: RemoteMCPServer
metadata:
  name: {{ include "kagent.fullname" . }}-mcp-grafana
  namespace: {{ include "kagent.namespace" . }}
  labels:
    {{- include "kagent.labels" . | nindent 4 }}
spec:
  protocol: SSE
  url: {{ printf "http://kagent.%s.svc.cluster.local:%v/sse" .Release.Namespace 8000 }}
  timeout: 30s
  sseReadTimeout: 5m0s
  description: "KAgent Grafana MCP"
