apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kagent.fullname" . }}-mcp-grafana
  namespace: {{ include "kagent.namespace" . }}
  labels:
    {{- include "kagent.labels" . | nindent 4 }}
type: Opaque
stringData:
  apiKey: {{ .Values.tools.grafana.apiKey | default "fake" }}
---
apiVersion: kagent.dev/v1alpha1
kind: ToolServer
metadata:
  name: {{ include "kagent.fullname" . }}-mcp-grafana
  namespace: kagent
spec:
  config:
    type: sse
    sse:
      sseReadTimeout: 5m0s
      url: "http://{{ include "kagent.fullname" . }}-controller.{{ .Release.Namespace }}.svc.cluster.local:8000/sse"
      timeout: 30s
  description: "KAgent Grafana MCP"
