apiVersion: v1
kind: Service
metadata:
  name: {{ include "kagent.fullname" . }}-ui
  namespace: {{ include "kagent.namespace" . }}
  labels:
    {{- include "kagent.ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - port: {{ .Values.ui.service.ports.port }}
      targetPort: {{ .Values.ui.service.ports.targetPort }}
      {{ if eq .Values.ui.service.type "NodePort" }}
      nodePort: {{ .Values.ui.service.ports.nodePort }}
      {{ end }}
      protocol: TCP
      name: ui
  selector:
    {{- include "kagent.ui.selectorLabels" . | nindent 4 }}
