apiVersion: kagent.dev/v1alpha1
kind: MCPServer
metadata:
  name: example-with-custom-registry
  namespace: kagent
spec:
  transportType: stdio
  stdioTransport: {}
  
  deployment:
    image: python:3.12-slim
    cmd: python
    args:
      - "-m"
      - "http.server"
    
    # Optional: Override the init container image
    # Useful when using a private registry or registry proxy
    initContainer:
      image: myregistry.com/agentgateway/agentgateway:0.9.0-musl
      imagePullPolicy: IfNotPresent
