-- +goose Up
ALTER TABLE agent_instance_checkpoint ADD COLUMN source_name TEXT NOT NULL DEFAULT '';

-- Existing wire IDs remain unchanged. New instances allocate independent IDs.
ALTER TABLE a2a_context ADD COLUMN context_id UUID;
UPDATE a2a_context SET context_id = id;
ALTER TABLE a2a_context ALTER COLUMN context_id SET NOT NULL;
ALTER TABLE a2a_context ADD CONSTRAINT a2a_context_binding_key UNIQUE (id, context_id);

ALTER TABLE agent_instance ADD COLUMN history_id UUID;
UPDATE agent_instance SET history_id = context_id;
ALTER TABLE agent_instance ALTER COLUMN history_id SET NOT NULL;
ALTER TABLE agent_instance DROP CONSTRAINT agent_instance_context_id_fkey;
ALTER TABLE agent_instance ADD CONSTRAINT agent_instance_context_binding_fkey
    FOREIGN KEY (history_id, context_id) REFERENCES a2a_context(id, context_id) ON DELETE RESTRICT;
ALTER TABLE agent_instance ADD CONSTRAINT agent_instance_history_key UNIQUE (history_id);

ALTER TABLE agent_instance_checkpoint RENAME COLUMN source_context_id TO source_history_id;
ALTER TABLE agent_instance_task RENAME COLUMN context_id TO history_id;
ALTER TABLE agent_instance_task_event RENAME COLUMN context_id TO history_id;

ALTER TABLE agent_instance_task ADD COLUMN position BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY;
WITH ordered AS (
    SELECT history_id, id, row_number() OVER (ORDER BY created_at, history_id, id) AS position
    FROM agent_instance_task
)
UPDATE agent_instance_task t SET position = ordered.position
FROM ordered WHERE t.history_id = ordered.history_id AND t.id = ordered.id;
DROP INDEX agent_instance_task_list_idx;
CREATE UNIQUE INDEX agent_instance_task_list_idx ON agent_instance_task (history_id, position);

-- Freeze materialized task state with the checkpoint; a paused source task can
-- advance without changing the projection restored by a subsequent fork.
CREATE TABLE agent_instance_checkpoint_task (
    checkpoint_id UUID NOT NULL REFERENCES agent_instance_checkpoint(id) ON DELETE CASCADE,
    id TEXT NOT NULL,
    data BYTEA NOT NULL,
    position BIGINT NOT NULL,
    initial_message_id TEXT,
    request_hash BYTEA,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (checkpoint_id, id),
    UNIQUE (checkpoint_id, position)
);
INSERT INTO agent_instance_checkpoint_task
SELECT c.id, t.id, t.data, t.position, t.initial_message_id, t.request_hash, t.created_at, t.updated_at
FROM agent_instance_checkpoint c
JOIN agent_instance_task head ON (head.history_id = c.source_history_id AND head.id = c.head_task_id)
JOIN agent_instance_task t ON (t.history_id = c.source_history_id AND t.position <= head.position)
WHERE NOT EXISTS (
    SELECT 1 FROM agent_instance_task changed
    WHERE changed.history_id = c.source_history_id AND changed.position <= head.position
      AND changed.updated_at > (SELECT created_at FROM agent_instance_task_event WHERE sequence = c.history_sequence)
);

-- +goose Down
DROP TABLE agent_instance_checkpoint_task;
DROP INDEX agent_instance_task_list_idx;
ALTER TABLE agent_instance_task DROP COLUMN position;
ALTER TABLE agent_instance_task RENAME COLUMN history_id TO context_id;
ALTER TABLE agent_instance_task_event RENAME COLUMN history_id TO context_id;
ALTER TABLE agent_instance_checkpoint RENAME COLUMN source_history_id TO source_context_id;
CREATE INDEX agent_instance_task_list_idx ON agent_instance_task (context_id, id);

ALTER TABLE agent_instance DROP CONSTRAINT agent_instance_context_binding_fkey;
-- Restore the old storage binding. Wire IDs remain available in protobuf data.
UPDATE agent_instance SET context_id = history_id;
ALTER TABLE agent_instance DROP COLUMN history_id;
ALTER TABLE agent_instance ADD CONSTRAINT agent_instance_context_id_fkey
    FOREIGN KEY (context_id) REFERENCES a2a_context(id) ON DELETE RESTRICT;
ALTER TABLE a2a_context DROP CONSTRAINT a2a_context_binding_key;
ALTER TABLE a2a_context DROP COLUMN context_id;
ALTER TABLE agent_instance_checkpoint DROP COLUMN source_name;
