// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_instance_tasks.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countAgentInstanceTasks = `-- name: CountAgentInstanceTasks :one
SELECT COUNT(*) FROM agent_instance_task
WHERE history_id = $1
  AND ($2::text = '' OR state = $2)
  AND ($3::timestamptz IS NULL
       OR status_timestamp > $3)
`

type CountAgentInstanceTasksParams struct {
	HistoryID            uuid.UUID
	State                string
	StatusTimestampAfter *time.Time
}

func (q *Queries) CountAgentInstanceTasks(ctx context.Context, arg CountAgentInstanceTasksParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAgentInstanceTasks, arg.HistoryID, arg.State, arg.StatusTimestampAfter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAgentInstanceTask = `-- name: CreateAgentInstanceTask :one
INSERT INTO agent_instance_task (
    history_id, id, state, status_timestamp, data, initial_message_id, request_hash
)
SELECT $1, $2, $3, $4, $5, $6, $7
WHERE NOT EXISTS (
    SELECT 1 FROM agent_instance_checkpoint
    WHERE source_history_id = $1 AND state = 'CREATING'
)
ON CONFLICT (history_id, initial_message_id)
    WHERE initial_message_id IS NOT NULL
DO NOTHING
RETURNING history_id, id, state, status_timestamp, data, created_at, updated_at, initial_message_id, request_hash, snapshot_atespace, snapshot_uri, snapshot_content_scope, history_sequence, position
`

type CreateAgentInstanceTaskParams struct {
	HistoryID        uuid.UUID
	ID               string
	State            string
	StatusTimestamp  *time.Time
	Data             []byte
	InitialMessageID *string
	RequestHash      []byte
}

func (q *Queries) CreateAgentInstanceTask(ctx context.Context, arg CreateAgentInstanceTaskParams) (AgentInstanceTask, error) {
	row := q.db.QueryRow(ctx, createAgentInstanceTask,
		arg.HistoryID,
		arg.ID,
		arg.State,
		arg.StatusTimestamp,
		arg.Data,
		arg.InitialMessageID,
		arg.RequestHash,
	)
	var i AgentInstanceTask
	err := row.Scan(
		&i.HistoryID,
		&i.ID,
		&i.State,
		&i.StatusTimestamp,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InitialMessageID,
		&i.RequestHash,
		&i.SnapshotAtespace,
		&i.SnapshotUri,
		&i.SnapshotContentScope,
		&i.HistorySequence,
		&i.Position,
	)
	return i, err
}

const getActiveAgentInstanceTask = `-- name: GetActiveAgentInstanceTask :one
SELECT history_id, id, state, status_timestamp, data, created_at, updated_at, initial_message_id, request_hash, snapshot_atespace, snapshot_uri, snapshot_content_scope, history_sequence, position FROM agent_instance_task
WHERE history_id = $1
  AND state NOT IN (
      'TASK_STATE_COMPLETED',
      'TASK_STATE_CANCELED',
      'TASK_STATE_FAILED',
      'TASK_STATE_REJECTED',
      'TASK_STATE_INPUT_REQUIRED',
      'TASK_STATE_AUTH_REQUIRED'
  )
`

func (q *Queries) GetActiveAgentInstanceTask(ctx context.Context, historyID uuid.UUID) (AgentInstanceTask, error) {
	row := q.db.QueryRow(ctx, getActiveAgentInstanceTask, historyID)
	var i AgentInstanceTask
	err := row.Scan(
		&i.HistoryID,
		&i.ID,
		&i.State,
		&i.StatusTimestamp,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InitialMessageID,
		&i.RequestHash,
		&i.SnapshotAtespace,
		&i.SnapshotUri,
		&i.SnapshotContentScope,
		&i.HistorySequence,
		&i.Position,
	)
	return i, err
}

const getActiveAgentInstanceTaskForUpdate = `-- name: GetActiveAgentInstanceTaskForUpdate :one
SELECT history_id, id, state, status_timestamp, data, created_at, updated_at, initial_message_id, request_hash, snapshot_atespace, snapshot_uri, snapshot_content_scope, history_sequence, position FROM agent_instance_task
WHERE history_id = $1
  AND state NOT IN (
      'TASK_STATE_COMPLETED',
      'TASK_STATE_CANCELED',
      'TASK_STATE_FAILED',
      'TASK_STATE_REJECTED',
      'TASK_STATE_INPUT_REQUIRED',
      'TASK_STATE_AUTH_REQUIRED'
  )
FOR UPDATE
`

// GetActiveAgentInstanceTaskForUpdate holds the instance's non-terminal task for the
// rest of the transaction so reclamation cannot overwrite concurrent progress.
func (q *Queries) GetActiveAgentInstanceTaskForUpdate(ctx context.Context, historyID uuid.UUID) (AgentInstanceTask, error) {
	row := q.db.QueryRow(ctx, getActiveAgentInstanceTaskForUpdate, historyID)
	var i AgentInstanceTask
	err := row.Scan(
		&i.HistoryID,
		&i.ID,
		&i.State,
		&i.StatusTimestamp,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InitialMessageID,
		&i.RequestHash,
		&i.SnapshotAtespace,
		&i.SnapshotUri,
		&i.SnapshotContentScope,
		&i.HistorySequence,
		&i.Position,
	)
	return i, err
}

const getAgentInstanceTask = `-- name: GetAgentInstanceTask :one
SELECT history_id, id, state, status_timestamp, data, created_at, updated_at, initial_message_id, request_hash, snapshot_atespace, snapshot_uri, snapshot_content_scope, history_sequence, position FROM agent_instance_task
WHERE history_id = $1 AND id = $2
`

type GetAgentInstanceTaskParams struct {
	HistoryID uuid.UUID
	ID        string
}

func (q *Queries) GetAgentInstanceTask(ctx context.Context, arg GetAgentInstanceTaskParams) (AgentInstanceTask, error) {
	row := q.db.QueryRow(ctx, getAgentInstanceTask, arg.HistoryID, arg.ID)
	var i AgentInstanceTask
	err := row.Scan(
		&i.HistoryID,
		&i.ID,
		&i.State,
		&i.StatusTimestamp,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InitialMessageID,
		&i.RequestHash,
		&i.SnapshotAtespace,
		&i.SnapshotUri,
		&i.SnapshotContentScope,
		&i.HistorySequence,
		&i.Position,
	)
	return i, err
}

const getAgentInstanceTaskByMessageID = `-- name: GetAgentInstanceTaskByMessageID :one
SELECT history_id, id, state, status_timestamp, data, created_at, updated_at, initial_message_id, request_hash, snapshot_atespace, snapshot_uri, snapshot_content_scope, history_sequence, position FROM agent_instance_task
WHERE history_id = $1 AND initial_message_id = $2
`

type GetAgentInstanceTaskByMessageIDParams struct {
	HistoryID        uuid.UUID
	InitialMessageID *string
}

func (q *Queries) GetAgentInstanceTaskByMessageID(ctx context.Context, arg GetAgentInstanceTaskByMessageIDParams) (AgentInstanceTask, error) {
	row := q.db.QueryRow(ctx, getAgentInstanceTaskByMessageID, arg.HistoryID, arg.InitialMessageID)
	var i AgentInstanceTask
	err := row.Scan(
		&i.HistoryID,
		&i.ID,
		&i.State,
		&i.StatusTimestamp,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InitialMessageID,
		&i.RequestHash,
		&i.SnapshotAtespace,
		&i.SnapshotUri,
		&i.SnapshotContentScope,
		&i.HistorySequence,
		&i.Position,
	)
	return i, err
}

const getAgentInstanceTaskForUpdate = `-- name: GetAgentInstanceTaskForUpdate :one
SELECT history_id, id, state, status_timestamp, data, created_at, updated_at, initial_message_id, request_hash, snapshot_atespace, snapshot_uri, snapshot_content_scope, history_sequence, position FROM agent_instance_task WHERE history_id = $1 AND id = $2 FOR UPDATE
`

type GetAgentInstanceTaskForUpdateParams struct {
	HistoryID uuid.UUID
	ID        string
}

func (q *Queries) GetAgentInstanceTaskForUpdate(ctx context.Context, arg GetAgentInstanceTaskForUpdateParams) (AgentInstanceTask, error) {
	row := q.db.QueryRow(ctx, getAgentInstanceTaskForUpdate, arg.HistoryID, arg.ID)
	var i AgentInstanceTask
	err := row.Scan(
		&i.HistoryID,
		&i.ID,
		&i.State,
		&i.StatusTimestamp,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InitialMessageID,
		&i.RequestHash,
		&i.SnapshotAtespace,
		&i.SnapshotUri,
		&i.SnapshotContentScope,
		&i.HistorySequence,
		&i.Position,
	)
	return i, err
}

const insertAgentInstanceTaskEvent = `-- name: InsertAgentInstanceTaskEvent :one
WITH inserted AS (
    INSERT INTO agent_instance_task_event
        (history_id, task_id, message_id, data, snapshot_atespace, snapshot_uri, snapshot_content_scope,
         task_position, initial_message_id, request_hash, created_at)
    VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, COALESCE($11::timestamptz, NOW()))
    ON CONFLICT (history_id, task_id, message_id)
        WHERE message_id IS NOT NULL
    DO NOTHING
    RETURNING sequence
)
SELECT sequence FROM inserted
UNION ALL
SELECT sequence FROM agent_instance_task_event
WHERE history_id = $1 AND task_id IS NOT DISTINCT FROM $2 AND message_id = $3
LIMIT 1
`

type InsertAgentInstanceTaskEventParams struct {
	HistoryID            uuid.UUID
	TaskID               *string
	MessageID            *string
	Data                 []byte
	SnapshotAtespace     *string
	SnapshotUri          *string
	SnapshotContentScope *string
	TaskPosition         *int64
	InitialMessageID     *string
	RequestHash          []byte
	CreatedAt            *time.Time
}

func (q *Queries) InsertAgentInstanceTaskEvent(ctx context.Context, arg InsertAgentInstanceTaskEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertAgentInstanceTaskEvent,
		arg.HistoryID,
		arg.TaskID,
		arg.MessageID,
		arg.Data,
		arg.SnapshotAtespace,
		arg.SnapshotUri,
		arg.SnapshotContentScope,
		arg.TaskPosition,
		arg.InitialMessageID,
		arg.RequestHash,
		arg.CreatedAt,
	)
	var sequence int64
	err := row.Scan(&sequence)
	return sequence, err
}

const insertCopiedAgentInstanceTask = `-- name: InsertCopiedAgentInstanceTask :exec
INSERT INTO agent_instance_task (
    history_id, id, state, status_timestamp, data, created_at, updated_at,
    initial_message_id, request_hash, snapshot_atespace, snapshot_uri,
    snapshot_content_scope, history_sequence, position
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
`

type InsertCopiedAgentInstanceTaskParams struct {
	HistoryID            uuid.UUID
	ID                   string
	State                string
	StatusTimestamp      *time.Time
	Data                 []byte
	CreatedAt            time.Time
	UpdatedAt            time.Time
	InitialMessageID     *string
	RequestHash          []byte
	SnapshotAtespace     *string
	SnapshotUri          *string
	SnapshotContentScope *string
	HistorySequence      *int64
	Position             int64
}

func (q *Queries) InsertCopiedAgentInstanceTask(ctx context.Context, arg InsertCopiedAgentInstanceTaskParams) error {
	_, err := q.db.Exec(ctx, insertCopiedAgentInstanceTask,
		arg.HistoryID,
		arg.ID,
		arg.State,
		arg.StatusTimestamp,
		arg.Data,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.InitialMessageID,
		arg.RequestHash,
		arg.SnapshotAtespace,
		arg.SnapshotUri,
		arg.SnapshotContentScope,
		arg.HistorySequence,
		arg.Position,
	)
	return err
}

const listAgentInstanceTaskEvents = `-- name: ListAgentInstanceTaskEvents :many
SELECT sequence, history_id, task_id, data, created_at, message_id, task_position, initial_message_id, request_hash, snapshot_atespace, snapshot_uri, snapshot_content_scope FROM agent_instance_task_event WHERE history_id = $1 ORDER BY sequence
`

func (q *Queries) ListAgentInstanceTaskEvents(ctx context.Context, historyID uuid.UUID) ([]AgentInstanceTaskEvent, error) {
	rows, err := q.db.Query(ctx, listAgentInstanceTaskEvents, historyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentInstanceTaskEvent
	for rows.Next() {
		var i AgentInstanceTaskEvent
		if err := rows.Scan(
			&i.Sequence,
			&i.HistoryID,
			&i.TaskID,
			&i.Data,
			&i.CreatedAt,
			&i.MessageID,
			&i.TaskPosition,
			&i.InitialMessageID,
			&i.RequestHash,
			&i.SnapshotAtespace,
			&i.SnapshotUri,
			&i.SnapshotContentScope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentInstanceTaskHistory = `-- name: ListAgentInstanceTaskHistory :many
SELECT task_id, data
FROM agent_instance_task_event
WHERE history_id = $1
  AND task_id = ANY($2::text[])
  AND message_id IS NOT NULL
ORDER BY sequence
`

type ListAgentInstanceTaskHistoryParams struct {
	HistoryID uuid.UUID
	TaskIds   []string
}

type ListAgentInstanceTaskHistoryRow struct {
	TaskID *string
	Data   []byte
}

func (q *Queries) ListAgentInstanceTaskHistory(ctx context.Context, arg ListAgentInstanceTaskHistoryParams) ([]ListAgentInstanceTaskHistoryRow, error) {
	rows, err := q.db.Query(ctx, listAgentInstanceTaskHistory, arg.HistoryID, arg.TaskIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgentInstanceTaskHistoryRow
	for rows.Next() {
		var i ListAgentInstanceTaskHistoryRow
		if err := rows.Scan(&i.TaskID, &i.Data); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentInstanceTasks = `-- name: ListAgentInstanceTasks :many
SELECT t.history_id, t.id, t.state, t.status_timestamp, t.data, t.created_at, t.updated_at, t.initial_message_id, t.request_hash, t.snapshot_atespace, t.snapshot_uri, t.snapshot_content_scope, t.history_sequence, t.position FROM agent_instance_task t
WHERE t.history_id = $1
  AND ($2::text = '' OR t.position > (
      SELECT cursor.position FROM agent_instance_task cursor
      WHERE cursor.history_id = $1 AND cursor.id = $2
  ))
  AND ($3::text = '' OR t.state = $3)
  AND ($4::timestamptz IS NULL
       OR t.status_timestamp > $4)
ORDER BY t.position
LIMIT $5
`

type ListAgentInstanceTasksParams struct {
	HistoryID            uuid.UUID
	AfterID              string
	State                string
	StatusTimestampAfter *time.Time
	PageSize             int32
}

func (q *Queries) ListAgentInstanceTasks(ctx context.Context, arg ListAgentInstanceTasksParams) ([]AgentInstanceTask, error) {
	rows, err := q.db.Query(ctx, listAgentInstanceTasks,
		arg.HistoryID,
		arg.AfterID,
		arg.State,
		arg.StatusTimestampAfter,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentInstanceTask
	for rows.Next() {
		var i AgentInstanceTask
		if err := rows.Scan(
			&i.HistoryID,
			&i.ID,
			&i.State,
			&i.StatusTimestamp,
			&i.Data,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.InitialMessageID,
			&i.RequestHash,
			&i.SnapshotAtespace,
			&i.SnapshotUri,
			&i.SnapshotContentScope,
			&i.HistorySequence,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAgentInstanceTaskSnapshot = `-- name: SetAgentInstanceTaskSnapshot :exec
UPDATE agent_instance_task SET
    snapshot_atespace = $3,
    snapshot_uri = $4,
    snapshot_content_scope = $5,
    history_sequence = $6
WHERE history_id = $1 AND id = $2
`

type SetAgentInstanceTaskSnapshotParams struct {
	HistoryID            uuid.UUID
	ID                   string
	SnapshotAtespace     *string
	SnapshotUri          *string
	SnapshotContentScope *string
	HistorySequence      *int64
}

func (q *Queries) SetAgentInstanceTaskSnapshot(ctx context.Context, arg SetAgentInstanceTaskSnapshotParams) error {
	_, err := q.db.Exec(ctx, setAgentInstanceTaskSnapshot,
		arg.HistoryID,
		arg.ID,
		arg.SnapshotAtespace,
		arg.SnapshotUri,
		arg.SnapshotContentScope,
		arg.HistorySequence,
	)
	return err
}

const upsertAgentInstanceTask = `-- name: UpsertAgentInstanceTask :one
INSERT INTO agent_instance_task (history_id, id, state, status_timestamp, data)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (history_id, id) DO UPDATE SET
    state = EXCLUDED.state,
    status_timestamp = EXCLUDED.status_timestamp,
    data = EXCLUDED.data,
    updated_at = NOW()
RETURNING history_id, id, state, status_timestamp, data, created_at, updated_at, initial_message_id, request_hash, snapshot_atespace, snapshot_uri, snapshot_content_scope, history_sequence, position
`

type UpsertAgentInstanceTaskParams struct {
	HistoryID       uuid.UUID
	ID              string
	State           string
	StatusTimestamp *time.Time
	Data            []byte
}

func (q *Queries) UpsertAgentInstanceTask(ctx context.Context, arg UpsertAgentInstanceTaskParams) (AgentInstanceTask, error) {
	row := q.db.QueryRow(ctx, upsertAgentInstanceTask,
		arg.HistoryID,
		arg.ID,
		arg.State,
		arg.StatusTimestamp,
		arg.Data,
	)
	var i AgentInstanceTask
	err := row.Scan(
		&i.HistoryID,
		&i.ID,
		&i.State,
		&i.StatusTimestamp,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InitialMessageID,
		&i.RequestHash,
		&i.SnapshotAtespace,
		&i.SnapshotUri,
		&i.SnapshotContentScope,
		&i.HistorySequence,
		&i.Position,
	)
	return i, err
}
