// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"time"

	"github.com/google/uuid"
	pgvector_go "github.com/pgvector/pgvector-go"
)

type A2aContext struct {
	ID        uuid.UUID
	UserID    string
	CreatedAt time.Time
	ContextID uuid.UUID
}

type AgentInstance struct {
	ID                 uuid.UUID
	UserID             string
	RequestID          string
	PreparedRevision   *string
	State              string
	Labels             []byte
	Data               []byte
	Operation          string
	ContextID          uuid.UUID
	SourceCheckpointID *uuid.UUID
	HistoryID          uuid.UUID
}

type AgentInstanceCheckpoint struct {
	ID                   uuid.UUID
	SourceInstanceID     uuid.UUID
	UserID               string
	RequestID            string
	HeadTaskID           string
	HistorySequence      int64
	SnapshotAtespace     string
	SnapshotUri          string
	SnapshotContentScope string
	TagUid               string
	State                string
	Data                 []byte
	SourceHistoryID      uuid.UUID
	PreparedRevision     *string
	SourceLabels         []byte
	SourceName           string
}

type AgentInstanceShare struct {
	ID         uuid.UUID
	InstanceID uuid.UUID
	Permission string
	TokenHash  []byte
	Data       []byte
}

type AgentInstanceTask struct {
	HistoryID            uuid.UUID
	ID                   string
	State                string
	StatusTimestamp      *time.Time
	Data                 []byte
	CreatedAt            time.Time
	UpdatedAt            time.Time
	InitialMessageID     *string
	RequestHash          []byte
	SnapshotAtespace     *string
	SnapshotUri          *string
	SnapshotContentScope *string
	HistorySequence      *int64
	Position             int64
}

type AgentInstanceTaskEvent struct {
	Sequence             int64
	HistoryID            uuid.UUID
	TaskID               *string
	Data                 []byte
	CreatedAt            time.Time
	MessageID            *string
	TaskPosition         *int64
	InitialMessageID     *string
	RequestHash          []byte
	SnapshotAtespace     *string
	SnapshotUri          *string
	SnapshotContentScope *string
}

type Memory struct {
	ID          string
	AgentName   *string
	UserID      *string
	Content     *string
	Embedding   pgvector_go.Vector
	Metadata    *string
	CreatedAt   *time.Time
	ExpiresAt   *time.Time
	AccessCount *int64
}

type RuntimeRevision struct {
	Revision              string
	Namespace             string
	AgentTemplateName     string
	AgentTemplateUid      string
	HarnessName           string
	HarnessUid            string
	SourceSnapshot        []byte
	EgressDestinations    []string
	ActorTemplateAtespace string
	ActorTemplateName     string
	ActorTemplateUid      string
	CreatedAt             time.Time
	UpdatedAt             time.Time
	AgentCard             []byte
	DeletionStartedAt     *time.Time
}

type ScheduledRun struct {
	ID                uuid.UUID
	Creator           string
	RequestID         string
	RequestHash       []byte
	Data              []byte
	CreatedAt         time.Time
	UpdatedAt         time.Time
	NextExecutionTime *time.Time
	DeletedAt         *time.Time
}

type ScheduledRunExecution struct {
	ID              uuid.UUID
	ScheduledRunID  uuid.UUID
	ScheduledTime   *time.Time
	ManualRequestID *string
	Data            []byte
	CreatedAt       time.Time
	Deadline        time.Time
	AgentInstanceID *uuid.UUID
	TaskID          *string
	CompletedAt     *time.Time
	NextAttemptAt   time.Time
	LeaseToken      *uuid.UUID
	State           string
}

type Tool struct {
	ID          string
	ServerName  string
	GroupKind   string
	CreatedAt   *time.Time
	UpdatedAt   *time.Time
	DeletedAt   *time.Time
	Description *string
}

type Toolserver struct {
	Name          string
	GroupKind     string
	CreatedAt     *time.Time
	UpdatedAt     *time.Time
	DeletedAt     *time.Time
	Description   *string
	LastConnected *time.Time
}
