// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scheduled_runs.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const advanceScheduledRun = `-- name: AdvanceScheduledRun :exec
UPDATE scheduled_run SET next_execution_time = $2 WHERE id = $1
`

type AdvanceScheduledRunParams struct {
	ID                uuid.UUID
	NextExecutionTime *time.Time
}

func (q *Queries) AdvanceScheduledRun(ctx context.Context, arg AdvanceScheduledRunParams) error {
	_, err := q.db.Exec(ctx, advanceScheduledRun, arg.ID, arg.NextExecutionTime)
	return err
}

const createScheduledRun = `-- name: CreateScheduledRun :one
INSERT INTO scheduled_run (id, creator, request_id, request_hash, data, next_execution_time)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (creator, request_id) DO NOTHING RETURNING id, creator, request_id, request_hash, data, next_execution_time, deleted_at
`

type CreateScheduledRunParams struct {
	ID                uuid.UUID
	Creator           string
	RequestID         string
	RequestHash       []byte
	Data              []byte
	NextExecutionTime *time.Time
}

func (q *Queries) CreateScheduledRun(ctx context.Context, arg CreateScheduledRunParams) (ScheduledRun, error) {
	row := q.db.QueryRow(ctx, createScheduledRun,
		arg.ID,
		arg.Creator,
		arg.RequestID,
		arg.RequestHash,
		arg.Data,
		arg.NextExecutionTime,
	)
	var i ScheduledRun
	err := row.Scan(
		&i.ID,
		&i.Creator,
		&i.RequestID,
		&i.RequestHash,
		&i.Data,
		&i.NextExecutionTime,
		&i.DeletedAt,
	)
	return i, err
}

const createScheduledRunExecution = `-- name: CreateScheduledRunExecution :one
INSERT INTO scheduled_run_execution (id, scheduled_run_id, scheduled_time, manual_request_id, data)
VALUES ($1, $2, $3, $4, $5) RETURNING id, scheduled_run_id, scheduled_time, manual_request_id, data, agent_instance_id, task_id, completed_at, next_attempt_at, lease_token, state
`

type CreateScheduledRunExecutionParams struct {
	ID              uuid.UUID
	ScheduledRunID  uuid.UUID
	ScheduledTime   *time.Time
	ManualRequestID *string
	Data            []byte
}

func (q *Queries) CreateScheduledRunExecution(ctx context.Context, arg CreateScheduledRunExecutionParams) (ScheduledRunExecution, error) {
	row := q.db.QueryRow(ctx, createScheduledRunExecution,
		arg.ID,
		arg.ScheduledRunID,
		arg.ScheduledTime,
		arg.ManualRequestID,
		arg.Data,
	)
	var i ScheduledRunExecution
	err := row.Scan(
		&i.ID,
		&i.ScheduledRunID,
		&i.ScheduledTime,
		&i.ManualRequestID,
		&i.Data,
		&i.AgentInstanceID,
		&i.TaskID,
		&i.CompletedAt,
		&i.NextAttemptAt,
		&i.LeaseToken,
		&i.State,
	)
	return i, err
}

const databaseNow = `-- name: DatabaseNow :one
SELECT clock_timestamp()::timestamptz AS now
`

func (q *Queries) DatabaseNow(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, databaseNow)
	var now time.Time
	err := row.Scan(&now)
	return now, err
}

const expireScheduledRunExecution = `-- name: ExpireScheduledRunExecution :one
UPDATE scheduled_run_execution SET state = 'TIMED_OUT', completed_at = clock_timestamp(), data = $2
WHERE id = $1 RETURNING id, scheduled_run_id, scheduled_time, manual_request_id, data, agent_instance_id, task_id, completed_at, next_attempt_at, lease_token, state
`

type ExpireScheduledRunExecutionParams struct {
	ID   uuid.UUID
	Data []byte
}

func (q *Queries) ExpireScheduledRunExecution(ctx context.Context, arg ExpireScheduledRunExecutionParams) (ScheduledRunExecution, error) {
	row := q.db.QueryRow(ctx, expireScheduledRunExecution, arg.ID, arg.Data)
	var i ScheduledRunExecution
	err := row.Scan(
		&i.ID,
		&i.ScheduledRunID,
		&i.ScheduledTime,
		&i.ManualRequestID,
		&i.Data,
		&i.AgentInstanceID,
		&i.TaskID,
		&i.CompletedAt,
		&i.NextAttemptAt,
		&i.LeaseToken,
		&i.State,
	)
	return i, err
}

const findManualScheduledRunExecution = `-- name: FindManualScheduledRunExecution :one
SELECT id, scheduled_run_id, scheduled_time, manual_request_id, data, agent_instance_id, task_id, completed_at, next_attempt_at, lease_token, state FROM scheduled_run_execution WHERE scheduled_run_id = $1 AND manual_request_id = $2
`

type FindManualScheduledRunExecutionParams struct {
	ScheduledRunID  uuid.UUID
	ManualRequestID *string
}

func (q *Queries) FindManualScheduledRunExecution(ctx context.Context, arg FindManualScheduledRunExecutionParams) (ScheduledRunExecution, error) {
	row := q.db.QueryRow(ctx, findManualScheduledRunExecution, arg.ScheduledRunID, arg.ManualRequestID)
	var i ScheduledRunExecution
	err := row.Scan(
		&i.ID,
		&i.ScheduledRunID,
		&i.ScheduledTime,
		&i.ManualRequestID,
		&i.Data,
		&i.AgentInstanceID,
		&i.TaskID,
		&i.CompletedAt,
		&i.NextAttemptAt,
		&i.LeaseToken,
		&i.State,
	)
	return i, err
}

const findScheduledRunRequest = `-- name: FindScheduledRunRequest :one
SELECT id, creator, request_id, request_hash, data, next_execution_time, deleted_at FROM scheduled_run WHERE creator = $1 AND request_id = $2
`

type FindScheduledRunRequestParams struct {
	Creator   string
	RequestID string
}

func (q *Queries) FindScheduledRunRequest(ctx context.Context, arg FindScheduledRunRequestParams) (ScheduledRun, error) {
	row := q.db.QueryRow(ctx, findScheduledRunRequest, arg.Creator, arg.RequestID)
	var i ScheduledRun
	err := row.Scan(
		&i.ID,
		&i.Creator,
		&i.RequestID,
		&i.RequestHash,
		&i.Data,
		&i.NextExecutionTime,
		&i.DeletedAt,
	)
	return i, err
}

const getDueScheduledRunsForUpdate = `-- name: GetDueScheduledRunsForUpdate :many
SELECT id, creator, request_id, request_hash, data, next_execution_time, deleted_at FROM scheduled_run
WHERE deleted_at IS NULL AND next_execution_time <= $2::timestamptz
ORDER BY next_execution_time, id LIMIT $1 FOR UPDATE SKIP LOCKED
`

type GetDueScheduledRunsForUpdateParams struct {
	Limit int32
	Now   time.Time
}

func (q *Queries) GetDueScheduledRunsForUpdate(ctx context.Context, arg GetDueScheduledRunsForUpdateParams) ([]ScheduledRun, error) {
	rows, err := q.db.Query(ctx, getDueScheduledRunsForUpdate, arg.Limit, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduledRun
	for rows.Next() {
		var i ScheduledRun
		if err := rows.Scan(
			&i.ID,
			&i.Creator,
			&i.RequestID,
			&i.RequestHash,
			&i.Data,
			&i.NextExecutionTime,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLeasedScheduledRunExecutionForUpdate = `-- name: GetLeasedScheduledRunExecutionForUpdate :one
SELECT id, scheduled_run_id, scheduled_time, manual_request_id, data, agent_instance_id, task_id, completed_at, next_attempt_at, lease_token, state FROM scheduled_run_execution
WHERE id = $1 AND lease_token = $2 AND next_attempt_at > clock_timestamp()
  AND state IN ('PENDING', 'RUNNING') FOR UPDATE
`

type GetLeasedScheduledRunExecutionForUpdateParams struct {
	ID         uuid.UUID
	LeaseToken *uuid.UUID
}

func (q *Queries) GetLeasedScheduledRunExecutionForUpdate(ctx context.Context, arg GetLeasedScheduledRunExecutionForUpdateParams) (ScheduledRunExecution, error) {
	row := q.db.QueryRow(ctx, getLeasedScheduledRunExecutionForUpdate, arg.ID, arg.LeaseToken)
	var i ScheduledRunExecution
	err := row.Scan(
		&i.ID,
		&i.ScheduledRunID,
		&i.ScheduledTime,
		&i.ManualRequestID,
		&i.Data,
		&i.AgentInstanceID,
		&i.TaskID,
		&i.CompletedAt,
		&i.NextAttemptAt,
		&i.LeaseToken,
		&i.State,
	)
	return i, err
}

const getScheduledRun = `-- name: GetScheduledRun :one
SELECT id, creator, request_id, request_hash, data, next_execution_time, deleted_at FROM scheduled_run WHERE creator = $1 AND id = $2
`

type GetScheduledRunParams struct {
	Creator string
	ID      uuid.UUID
}

func (q *Queries) GetScheduledRun(ctx context.Context, arg GetScheduledRunParams) (ScheduledRun, error) {
	row := q.db.QueryRow(ctx, getScheduledRun, arg.Creator, arg.ID)
	var i ScheduledRun
	err := row.Scan(
		&i.ID,
		&i.Creator,
		&i.RequestID,
		&i.RequestHash,
		&i.Data,
		&i.NextExecutionTime,
		&i.DeletedAt,
	)
	return i, err
}

const getScheduledRunExecution = `-- name: GetScheduledRunExecution :one
SELECT e.id, e.scheduled_run_id, e.scheduled_time, e.manual_request_id, e.data, e.agent_instance_id, e.task_id, e.completed_at, e.next_attempt_at, e.lease_token, e.state FROM scheduled_run_execution e JOIN scheduled_run s ON s.id = e.scheduled_run_id
WHERE s.creator = $1 AND e.id = $2
`

type GetScheduledRunExecutionParams struct {
	Creator string
	ID      uuid.UUID
}

func (q *Queries) GetScheduledRunExecution(ctx context.Context, arg GetScheduledRunExecutionParams) (ScheduledRunExecution, error) {
	row := q.db.QueryRow(ctx, getScheduledRunExecution, arg.Creator, arg.ID)
	var i ScheduledRunExecution
	err := row.Scan(
		&i.ID,
		&i.ScheduledRunID,
		&i.ScheduledTime,
		&i.ManualRequestID,
		&i.Data,
		&i.AgentInstanceID,
		&i.TaskID,
		&i.CompletedAt,
		&i.NextAttemptAt,
		&i.LeaseToken,
		&i.State,
	)
	return i, err
}

const getScheduledRunExecutionForUpdate = `-- name: GetScheduledRunExecutionForUpdate :one
SELECT e.id, e.scheduled_run_id, e.scheduled_time, e.manual_request_id, e.data, e.agent_instance_id, e.task_id, e.completed_at, e.next_attempt_at, e.lease_token, e.state FROM scheduled_run_execution e JOIN scheduled_run s ON s.id = e.scheduled_run_id
WHERE s.creator = $1 AND e.id = $2 FOR UPDATE OF e
`

type GetScheduledRunExecutionForUpdateParams struct {
	Creator string
	ID      uuid.UUID
}

func (q *Queries) GetScheduledRunExecutionForUpdate(ctx context.Context, arg GetScheduledRunExecutionForUpdateParams) (ScheduledRunExecution, error) {
	row := q.db.QueryRow(ctx, getScheduledRunExecutionForUpdate, arg.Creator, arg.ID)
	var i ScheduledRunExecution
	err := row.Scan(
		&i.ID,
		&i.ScheduledRunID,
		&i.ScheduledTime,
		&i.ManualRequestID,
		&i.Data,
		&i.AgentInstanceID,
		&i.TaskID,
		&i.CompletedAt,
		&i.NextAttemptAt,
		&i.LeaseToken,
		&i.State,
	)
	return i, err
}

const getScheduledRunForUpdate = `-- name: GetScheduledRunForUpdate :one
SELECT id, creator, request_id, request_hash, data, next_execution_time, deleted_at FROM scheduled_run WHERE creator = $1 AND id = $2 FOR UPDATE
`

type GetScheduledRunForUpdateParams struct {
	Creator string
	ID      uuid.UUID
}

func (q *Queries) GetScheduledRunForUpdate(ctx context.Context, arg GetScheduledRunForUpdateParams) (ScheduledRun, error) {
	row := q.db.QueryRow(ctx, getScheduledRunForUpdate, arg.Creator, arg.ID)
	var i ScheduledRun
	err := row.Scan(
		&i.ID,
		&i.Creator,
		&i.RequestID,
		&i.RequestHash,
		&i.Data,
		&i.NextExecutionTime,
		&i.DeletedAt,
	)
	return i, err
}

const leaseScheduledRunExecutions = `-- name: LeaseScheduledRunExecutions :many
WITH candidates AS (
    SELECT id FROM scheduled_run_execution
    WHERE state IN ('PENDING', 'RUNNING') AND next_attempt_at <= clock_timestamp()
    ORDER BY next_attempt_at, id LIMIT $1 FOR UPDATE SKIP LOCKED
)
UPDATE scheduled_run_execution e
SET lease_token = $2::uuid, next_attempt_at = clock_timestamp() + interval '30 seconds'
FROM candidates c WHERE e.id = c.id RETURNING e.id, e.scheduled_run_id, e.scheduled_time, e.manual_request_id, e.data, e.agent_instance_id, e.task_id, e.completed_at, e.next_attempt_at, e.lease_token, e.state
`

type LeaseScheduledRunExecutionsParams struct {
	Limit      int32
	LeaseToken uuid.UUID
}

func (q *Queries) LeaseScheduledRunExecutions(ctx context.Context, arg LeaseScheduledRunExecutionsParams) ([]ScheduledRunExecution, error) {
	rows, err := q.db.Query(ctx, leaseScheduledRunExecutions, arg.Limit, arg.LeaseToken)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduledRunExecution
	for rows.Next() {
		var i ScheduledRunExecution
		if err := rows.Scan(
			&i.ID,
			&i.ScheduledRunID,
			&i.ScheduledTime,
			&i.ManualRequestID,
			&i.Data,
			&i.AgentInstanceID,
			&i.TaskID,
			&i.CompletedAt,
			&i.NextAttemptAt,
			&i.LeaseToken,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduledRunExecutions = `-- name: ListScheduledRunExecutions :many
SELECT e.id, e.scheduled_run_id, e.scheduled_time, e.manual_request_id, e.data, e.agent_instance_id, e.task_id, e.completed_at, e.next_attempt_at, e.lease_token, e.state FROM scheduled_run_execution e JOIN scheduled_run s ON s.id = e.scheduled_run_id
WHERE s.creator = $1 AND e.scheduled_run_id = $2
  AND ($4::uuid IS NULL OR e.id < $4::uuid)
ORDER BY e.id DESC LIMIT $3
`

type ListScheduledRunExecutionsParams struct {
	Creator        string
	ScheduledRunID uuid.UUID
	Limit          int32
	AfterID        *uuid.UUID
}

func (q *Queries) ListScheduledRunExecutions(ctx context.Context, arg ListScheduledRunExecutionsParams) ([]ScheduledRunExecution, error) {
	rows, err := q.db.Query(ctx, listScheduledRunExecutions,
		arg.Creator,
		arg.ScheduledRunID,
		arg.Limit,
		arg.AfterID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduledRunExecution
	for rows.Next() {
		var i ScheduledRunExecution
		if err := rows.Scan(
			&i.ID,
			&i.ScheduledRunID,
			&i.ScheduledTime,
			&i.ManualRequestID,
			&i.Data,
			&i.AgentInstanceID,
			&i.TaskID,
			&i.CompletedAt,
			&i.NextAttemptAt,
			&i.LeaseToken,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduledRuns = `-- name: ListScheduledRuns :many
SELECT id, creator, request_id, request_hash, data, next_execution_time, deleted_at FROM scheduled_run WHERE creator = $1 AND deleted_at IS NULL
  AND ($3::uuid IS NULL OR id > $3::uuid)
ORDER BY id LIMIT $2
`

type ListScheduledRunsParams struct {
	Creator string
	Limit   int32
	AfterID *uuid.UUID
}

func (q *Queries) ListScheduledRuns(ctx context.Context, arg ListScheduledRunsParams) ([]ScheduledRun, error) {
	rows, err := q.db.Query(ctx, listScheduledRuns, arg.Creator, arg.Limit, arg.AfterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduledRun
	for rows.Next() {
		var i ScheduledRun
		if err := rows.Scan(
			&i.ID,
			&i.Creator,
			&i.RequestID,
			&i.RequestHash,
			&i.Data,
			&i.NextExecutionTime,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveScheduledRun = `-- name: SaveScheduledRun :one
UPDATE scheduled_run SET data = $2, next_execution_time = $3, deleted_at = $4
WHERE id = $1 RETURNING id, creator, request_id, request_hash, data, next_execution_time, deleted_at
`

type SaveScheduledRunParams struct {
	ID                uuid.UUID
	Data              []byte
	NextExecutionTime *time.Time
	DeletedAt         *time.Time
}

func (q *Queries) SaveScheduledRun(ctx context.Context, arg SaveScheduledRunParams) (ScheduledRun, error) {
	row := q.db.QueryRow(ctx, saveScheduledRun,
		arg.ID,
		arg.Data,
		arg.NextExecutionTime,
		arg.DeletedAt,
	)
	var i ScheduledRun
	err := row.Scan(
		&i.ID,
		&i.Creator,
		&i.RequestID,
		&i.RequestHash,
		&i.Data,
		&i.NextExecutionTime,
		&i.DeletedAt,
	)
	return i, err
}

const setScheduledRunExecutionInstance = `-- name: SetScheduledRunExecutionInstance :one
UPDATE scheduled_run_execution SET agent_instance_id = $2 WHERE id = $1 RETURNING id, scheduled_run_id, scheduled_time, manual_request_id, data, agent_instance_id, task_id, completed_at, next_attempt_at, lease_token, state
`

type SetScheduledRunExecutionInstanceParams struct {
	ID              uuid.UUID
	AgentInstanceID *uuid.UUID
}

func (q *Queries) SetScheduledRunExecutionInstance(ctx context.Context, arg SetScheduledRunExecutionInstanceParams) (ScheduledRunExecution, error) {
	row := q.db.QueryRow(ctx, setScheduledRunExecutionInstance, arg.ID, arg.AgentInstanceID)
	var i ScheduledRunExecution
	err := row.Scan(
		&i.ID,
		&i.ScheduledRunID,
		&i.ScheduledTime,
		&i.ManualRequestID,
		&i.Data,
		&i.AgentInstanceID,
		&i.TaskID,
		&i.CompletedAt,
		&i.NextAttemptAt,
		&i.LeaseToken,
		&i.State,
	)
	return i, err
}

const updateScheduledRunExecution = `-- name: UpdateScheduledRunExecution :execrows
UPDATE scheduled_run_execution
SET state = $2, task_id = COALESCE(task_id, $3), data = $4,
    completed_at = CASE WHEN $2::text IN ('SUCCEEDED', 'FAILED', 'TIMED_OUT') THEN clock_timestamp() END,
    next_attempt_at = clock_timestamp() + interval '1 second', lease_token = NULL
WHERE id = $1 AND lease_token = $5::uuid AND next_attempt_at > clock_timestamp()
    AND state IN ('PENDING', 'RUNNING')
    AND (task_id IS NULL OR $3::text IS NULL OR task_id = $3)
`

type UpdateScheduledRunExecutionParams struct {
	ID         uuid.UUID
	State      string
	TaskID     *string
	Data       []byte
	LeaseToken uuid.UUID
}

func (q *Queries) UpdateScheduledRunExecution(ctx context.Context, arg UpdateScheduledRunExecutionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateScheduledRunExecution,
		arg.ID,
		arg.State,
		arg.TaskID,
		arg.Data,
		arg.LeaseToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
