ARG DOCKER_REGISTRY=ghcr.io
# TODO: use latest tag once it is available
ARG VERSION=0.6.7
FROM $DOCKER_REGISTRY/kagent-dev/kagent/kagent-adk:$VERSION

WORKDIR /app

COPY  {{.Name}}/ {{.Name}}/
COPY  pyproject.toml pyproject.toml
COPY  README.md README.md
COPY  .python-version .python-version

RUN uv sync

CMD ["{{.Name}}"]
