apiVersion: kagent.dev/v1alpha2
kind: Agent
metadata:
  name: currency-converter-agent
spec:
  description: A currency converter LangGraph agent that can convert currencies
  type: BYO
  byo:
    deployment:
      image: localhost:5001/langgraph-currency:latest
      env:
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: kagent-google
              key: GOOGLE_API_KEY
