# Default values for autogenstudio
replicaCount: 1

global:
  tag: ""

openai:
  secretName: "autogenstudio-openai"
  apiKey: ""
  secretKey: "OPENAI_API_KEY"

controller:
  image:
    registry: ghcr.io
    repository: kagent-dev/kagent/controller
    tag: ""  # Will default to global, then Chart version
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

app:
  image:
    registry: ghcr.io
    repository: kagent-dev/kagent/app
    tag: ""  # Will default to global, then Chart version
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi

service:
  type: ClusterIP
  port: 80
  targetPort: 80

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000